baseURL = "/"
languageCode = "en-us"
title = "Sysl"
description = "Sysl /ˈsɪzəl/ is a system specification language"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Sysl"
  github = "anz-bank"
[[menu.main]]
    weight = 1
    name = "Docs"
    url = "/docs/"
[[menu.main]]
    weight = 1
    name = "Examples"
    url = "/examples/"
[[menu.main]]
    weight = 1
    name = "Guides"
    url = "/guides/"
[[menu.main]]
    weight = 2
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    weight = 3
    name = "FAQ"
    url = "/faq/"
