name: Generate-Tag

on:
  push:
    branches:
      - master

jobs:
  generate-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      # Generate tag if commit message contains #major or #patch or #patch
      - name: Bump version and push tag
        id: generate_tag
        uses: anz-bank/github-tag-action@master
        env:
          # An action in a workflow run can't trigger a new workflow run.
          # When you use GITHUB_TOKEN in your actions, all of the interactions 
          # with the repository are on behalf of the Github-actions bot. 
          # The operations act by Github-actions bot cannot trigger a new workflow run.
          # More details: https://help.github.com/en/actions/reference/events-that-trigger-workflows#about-workflow-events
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          WITH_V: true

      # Generate changelog for new major or minor version.
      - name: Generate changelog
        if: steps.generate_tag.outputs.tag_generated == 1 && (steps.generate_tag.outputs.bump_ver == 'major' || steps.generate_tag.outputs.bump_ver == 'minor')
        uses: docker://ferrarimarco/github-changelog-generator:latest
        with:
          args: -u anz-bank -p sysl --output ${{ format('CHANGELOG/CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }} --header-label="${{ format('# CHANGELOG-{0}.{1}', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}" --since-tag=${{ steps.generate_tag.outputs.last_tag }} --no-unreleased --max-issues 2
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set since tag
        if: steps.generate_tag.outputs.tag_generated == 1 && steps.generate_tag.outputs.bump_ver == 'patch'
        run: echo ::set-env name=since_tag::$(git describe --tags --abbrev=0 ${{ format('v{0}.{1}.0^', steps.generate_tag.outputs.last_major, steps.generate_tag.outputs.last_minor) }})

      # Rewrite changelog for new patch version.
      - name: Rewrite changelog
        if: env.since_tag != ''
        uses: docker://ferrarimarco/github-changelog-generator:latest
        with:
          args: -u anz-bank -p sysl --output ${{ format('CHANGELOG/CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }} --header-label="${{ format('# CHANGELOG-{0}.{1}', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}" --since-tag=${{ env.since_tag }} --no-unreleased --max-issues 2
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create CHANGELOG generated PR
        if: steps.generate_tag.outputs.tag_generated == 1
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ format('changelog/v{0}.{1}', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}
          branch-suffix: short-commit-hash
          base: master
          commit-message: "docs: generate ${{ format('CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}"
          title: "docs: generate ${{ format('CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}"
