name: Build and Test

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    name: Build Go and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

        # Needed for changelog generation by goreleaser
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get dependencies
        run: make deps

      - name: Test
        run: make coverage
        timeout-minutes: 3
        env:
          SYSL_PLANTUML: http://www.plantuml.com/plantuml

      - name: Set GOVERSION environment variable
        run: echo ::set-env name=GOVERSION::$(go version | awk '{print $3, $4;}')

      - name: Build sysl binary via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --snapshot --skip-publish --rm-dist --debug -f .github/goreleaser_configs/.goreleaser-${{ matrix.os }}.yml

      # sysl_linux_amd64: according to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
      # Ubuntu 18.04 supports 64-bit applications
      - name: Install sysl (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mkdir $PWD/bin && cp ./dist/sysl_linux_amd64/sysl $PWD/bin/sysl
      
      # sysl_darwin_amd64: according to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
      # macOS Catalina 10.15 supports 64-bit applications
      - name: Install sysl (macOS)
        if: matrix.os == 'macOS-latest'
        run: mkdir $PWD/bin && cp ./dist/sysl_darwin_amd64/sysl $PWD/bin/sysl

      - name: Test installed 
        run: ./scripts/test-gosysl.sh
        env:
          GOPATH: .
          SYSL_PLANTUML: http://www.plantuml.com/plantuml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-test-windows:
    name: Build Go and Test (Windows)
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

      # Needed for changelog generation by goreleaser
    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Get dependencies
      run: make deps

    - name: Test
      run: .\scripts\test-with-coverage-windows.bat
      timeout-minutes: 3
      env:
        SYSL_PLANTUML: http://www.plantuml.com/plantuml

    - name: Set GOVERSION environment variable (Windows)
      run: $Env:GOVERSION=(go version | %{($_ -split " ")[-2,-1] -join " "}); echo $Env:GOVERSION

    - name: Build sysl binary via goreleaser (Windows)
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --snapshot --skip-publish --rm-dist --debug -f .github/goreleaser_configs/.goreleaser-windows-latest.yml

    # sysl_windows_amd64: according to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # Windows Server 2019 supports 64-bit applications
    - name: Install sysl
      run: md .\bin; copy .\dist\sysl_windows_amd64\sysl.exe .\bin\sysl.exe

    - name: Test installed
      run: .\scripts\test-gosysl.bat
      env:
        SYSL_PLANTUML: http://www.plantuml.com/plantuml

  build-and-test-sysl_js:
    name: Build and test sysl_js on linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Check out code
        uses: actions/checkout@master

      - name: Install and test sysl_js
        run: |
          npm install --prefix unsorted/sysl_js
          npm test --prefix unsorted/sysl_js
        env:
          NPM_AUTH_TOKEN: "SOME-RANDOM-KEY"

  build-docker:
    name: Builds the sysl docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: docker.io/anzbank/sysl
          tag_with_ref: true
          add_git_labels: true
          tags: latest
          push: false
          labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.url=https://sysl.io
